-- Phase 2: Consolidation Technique & Documents

-- 1. Enrichissement de tb_vehicules
ALTER TABLE public.tb_vehicules 
ADD COLUMN IF NOT EXISTS numero_chassis varchar(50),
ADD COLUMN IF NOT EXISTS date_achat date,
ADD COLUMN IF NOT EXISTS valeur_achat numeric(12,2),
ADD COLUMN IF NOT EXISTS type_carburant varchar(20), -- Essence, Diesel, Hybrid, Electric
ADD COLUMN IF NOT EXISTS capacite_reservoir numeric(10,2);

-- 2. Enrichissement de tb_chauffeurs
ALTER TABLE public.tb_chauffeurs 
ADD COLUMN IF NOT EXISTS email varchar(100),
ADD COLUMN IF NOT EXISTS type_contrat varchar(50), -- CDD, CDI, Prestataire
ADD COLUMN IF NOT EXISTS date_embauche date;

-- 3. Enrichissement de tb_missions (pour calcul rentabilité/TCO)
ALTER TABLE public.tb_missions 
ADD COLUMN IF NOT EXISTS kilometrage_fin integer;

-- 4. Table universelle pour les documents (Fichiers)
CREATE TABLE IF NOT EXISTS public.tb_documents (
    document_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(100) NOT NULL,
    type_document varchar(50) NOT NULL, -- Assurance, Carte Grise, Permis, Contrat, Controle Technique
    fichier_url text NOT NULL, -- URL Supabase Storage
    date_expiration date,
    entite_type varchar(20) NOT NULL, -- Vehicule, Chauffeur
    entite_id bigint NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.tb_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acces total pour authentifiés sur documents" ON public.tb_documents FOR ALL USING (true);

-- Trigger updated_at pour documents
CREATE TRIGGER update_tb_documents_updated_at BEFORE UPDATE ON public.tb_documents FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Index
CREATE INDEX IF NOT EXISTS idx_documents_entite ON public.tb_documents(entite_type, entite_id);
CREATE INDEX IF NOT EXISTS idx_documents_expiration ON public.tb_documents(date_expiration);
