-- Phase 1: Comptabilité et Réservations

-- 1. Ajout de colonnes financières à tb_missions
ALTER TABLE public.tb_missions 
ADD COLUMN IF NOT EXISTS montant_total numeric(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS acompte numeric(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS solde numeric(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS devise varchar(10) DEFAULT 'USD';

-- 1b. Ajout de devise à tb_remboursements
ALTER TABLE public.tb_remboursements
ADD COLUMN IF NOT EXISTS devise varchar(10) DEFAULT 'USD';

-- 2. Table des paiements (Revenus des missions)
CREATE TABLE IF NOT EXISTS public.tb_paiements (
    paiement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id bigint REFERENCES public.tb_missions(mission_id) ON DELETE CASCADE,
    montant numeric(12,2) NOT NULL,
    devise varchar(10) DEFAULT 'USD',
    date_paiement timestamp with time zone DEFAULT now(),
    methode_paiement varchar(50), -- Cash, Mobile Money, Carte, etc.
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 3. Table des dépenses (Carburant, Maintenance, etc.)
CREATE TABLE IF NOT EXISTS public.tb_depenses (
    depense_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicule_id bigint REFERENCES public.tb_vehicules(vehicule_id) ON DELETE SET NULL,
    chauffeur_id bigint REFERENCES public.tb_chauffeurs(chauffeur_id) ON DELETE SET NULL,
    maintenance_id bigint REFERENCES public.tb_maintenance(maintenance_id) ON DELETE SET NULL,
    categorie varchar(50) NOT NULL, -- Carburant, Maintenance, Salaire, Autre
    montant numeric(12,2) NOT NULL,
    devise varchar(10) DEFAULT 'USD',
    description text,
    date_depense timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 4. Table de la caisse (Journal des flux réels)
CREATE TABLE IF NOT EXISTS public.tb_caisse (
    transaction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(10) CHECK (type IN ('Entrée', 'Sortie')),
    montant numeric(12,2) NOT NULL,
    devise varchar(10) DEFAULT 'USD',
    source_type varchar(50), -- Mission, Remboursement, Depense, Manuel
    source_id bigint, -- ID de l'entité source
    description text,
    date_transaction timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.tb_paiements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tb_depenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tb_caisse ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Simple Authenticated Access)
CREATE POLICY "Acces total pour authentifiés sur paiements" ON public.tb_paiements FOR ALL USING (true);
CREATE POLICY "Acces total pour authentifiés sur depenses" ON public.tb_depenses FOR ALL USING (true);
CREATE POLICY "Acces total pour authentifiés sur caisse" ON public.tb_caisse FOR ALL USING (true);

-- Trigger for updated_at
CREATE TRIGGER update_tb_paiements_updated_at BEFORE UPDATE ON public.tb_paiements FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_tb_depenses_updated_at BEFORE UPDATE ON public.tb_depenses FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Index pour la performance
CREATE INDEX IF NOT EXISTS idx_paiements_mission ON public.tb_paiements(mission_id);
CREATE INDEX IF NOT EXISTS idx_depenses_vehicule ON public.tb_depenses(vehicule_id);
CREATE INDEX IF NOT EXISTS idx_caisse_date ON public.tb_caisse(date_transaction);
